name = "MonitoredQuantumCircuits"
uuid = "d8bf802c-9929-44b5-8e59-9c739daaeb6f"
authors = ["Quinten Preiss"]
version = "1.0.0-DEV"

[deps]
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[compat]
julia = "1.9.2"
