name = "MonitoredQuantumCircuits"
uuid = "d8bf802c-9929-44b5-8e59-9c739daaeb6f"
authors = ["Quinten Preiss"]
version = "0.2.0"

[deps]
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
QuantumClifford = "0525e862-1e90-11e9-3e4d-1b39d7109de1"

[weakdeps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[extensions]
MonitoredQuantumCircuitsCUDAExt = "CUDA"
MonitoredQuantumCircuitsMPIExt = "MPI"
MonitoredQuantumCircuitsMakieExt = "Makie"

[compat]
CUDA = "5.7"
Graphs = "1.11"
MPI = "0.20"
MPIPreferences = "0.20"
Makie = "0.22"
PythonCall = "0.9"
QuantumClifford = "0.10"
CondaPkg = "0.2"
julia = "1.11"

[extras]
MPIPreferences = "3da0fdf6-3ccc-4f1b-acd9-58baa6c99267"
