name = "MonitoredQuantumCircuits"
uuid = "d8bf802c-9929-44b5-8e59-9c739daaeb6f"
authors = ["Quinten Preiss"]
version = "0.1.0-DEV"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"

[compat]
julia = "1.9.2"
